/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.module.client.view;

import framework.module.config.model.classes.ClassConfig;

/**
 *
 * @author angel
 */
public class Update_client extends javax.swing.JFrame {

    public static String DNI;
    /**
     * Creates new form Menu
     */
    public Update_client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grouppremium = new javax.swing.ButtonGroup();
        groupstate = new javax.swing.ButtonGroup();
        JFC_avatar = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        lblusuarios = new javax.swing.JLabel();
        lbladministrador = new javax.swing.JLabel();
        lblcliente = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblconfiguracion = new javax.swing.JLabel();
        lblajustes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblinicios = new javax.swing.JLabel();
        lblinicio = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtconfirm = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblvolver = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnaceptar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtavatar = new javax.swing.JTextField();
        btnavatar = new javax.swing.JButton();
        statetrue = new javax.swing.JRadioButton();
        statefalse = new javax.swing.JRadioButton();
        txtname = new javax.swing.JTextField();
        txtsurname = new javax.swing.JTextField();
        checkDNI = new javax.swing.JLabel();
        checkpass = new javax.swing.JLabel();
        checkavatar = new javax.swing.JLabel();
        checkuser = new javax.swing.JLabel();
        checkname = new javax.swing.JLabel();
        checkstate = new javax.swing.JLabel();
        checksurname = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtdatebirthday = new com.toedter.calendar.JDateChooser();
        txtmobilephone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtdtos = new javax.swing.JTextField();
        txttype_client = new javax.swing.JTextField();
        checkemail = new javax.swing.JLabel();
        checkmobilephone = new javax.swing.JLabel();
        checkdatebirthday = new javax.swing.JLabel();
        checkshopping = new javax.swing.JLabel();
        checkpremium = new javax.swing.JLabel();
        checkdtos = new javax.swing.JLabel();
        checktype_client = new javax.swing.JLabel();
        txtshopping = new javax.swing.JTextField();
        premiumtrue = new javax.swing.JRadioButton();
        premiumfalse = new javax.swing.JRadioButton();
        showpass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbltitulo.setBackground(java.awt.Color.white);
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/titulo.JPG"))); // NOI18N
        jPanel2.add(lbltitulo, java.awt.BorderLayout.CENTER);
        jPanel2.add(jSeparator2, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(java.awt.Color.white);

        lblusuarios.setFont(new java.awt.Font("Purisa", 3, 15)); // NOI18N
        lblusuarios.setForeground(java.awt.Color.blue);
        lblusuarios.setText("Usuarios");

        lbladministrador.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lbladministrador.setForeground(java.awt.Color.cyan);
        lbladministrador.setText("Administrador");
        lbladministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladministradorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbladministradorMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbladministradorMouseEntered(evt);
            }
        });

        lblcliente.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblcliente.setForeground(java.awt.Color.cyan);
        lblcliente.setText("Cliente");
        lblcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblclienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblclienteMouseEntered(evt);
            }
        });

        lblusuario.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblusuario.setForeground(java.awt.Color.cyan);
        lblusuario.setText("Usuario");
        lblusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblusuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblusuarioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblusuarioMouseEntered(evt);
            }
        });

        lblconfiguracion.setFont(new java.awt.Font("Purisa", 3, 15)); // NOI18N
        lblconfiguracion.setForeground(java.awt.Color.blue);
        lblconfiguracion.setText("Configuración");

        lblajustes.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblajustes.setForeground(java.awt.Color.cyan);
        lblajustes.setText("Ajustes");
        lblajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblajustesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblajustesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblajustesMouseEntered(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblinicios.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblinicios.setForeground(java.awt.Color.blue);
        lblinicios.setText("Inicio");

        lblinicio.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblinicio.setForeground(java.awt.Color.cyan);
        lblinicio.setText("Inicio");
        lblinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblinicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblinicioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblinicioMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinicios)
                    .addComponent(lblusuarios)
                    .addComponent(lblconfiguracion)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinicio)
                            .addComponent(lblcliente)
                            .addComponent(lbladministrador)
                            .addComponent(lblusuario)
                            .addComponent(lblajustes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblinicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinicio)
                .addGap(18, 18, 18)
                .addComponent(lblusuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbladministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblusuario)
                .addGap(18, 18, 18)
                .addComponent(lblconfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblajustes)
                .addContainerGap(252, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(java.awt.Color.lightGray);

        txtconfirm.setForeground(java.awt.Color.white);
        txtconfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtconfirm.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(java.awt.Color.white);

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 3, 48)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Modificar Cliente");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(java.awt.Color.white);

        lblvolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png"))); // NOI18N
        lblvolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvolverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvolverMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvolverMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblvolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblvolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel8.setBackground(java.awt.Color.white);
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(java.awt.Color.white);
        jPanel11.setPreferredSize(new java.awt.Dimension(442, 116));

        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(btnaceptar)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnaceptar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel12.setBackground(java.awt.Color.white);
        jPanel12.setPreferredSize(new java.awt.Dimension(443, 116));

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(btncancelar)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncancelar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel12, java.awt.BorderLayout.LINE_END);

        jPanel3.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel7.setBackground(java.awt.Color.white);

        jLabel12.setText("DNI:");

        jLabel13.setText("Usuario:");

        jLabel14.setText("Contraseña:");

        jLabel15.setText("Avatar:");

        jLabel16.setText("Estado:");

        jLabel17.setText("Nombre:");

        jLabel18.setText("Apellidos:");

        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassFocusLost(evt);
            }
        });
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpassMouseClicked(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });

        txtuser.setText("example: user");
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuserKeyReleased(evt);
            }
        });

        txtDNI.setText("example: 12345678Z");
        txtDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNIFocusLost(evt);
            }
        });
        txtDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDNIMouseClicked(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDNIKeyReleased(evt);
            }
        });

        txtavatar.setText("/root");

        btnavatar.setText("Archivo");

        groupstate.add(statetrue);
        statetrue.setSelected(true);
        statetrue.setText("Conectado");

        groupstate.add(statefalse);
        statefalse.setText("No conectado");

        txtname.setText("example: name");
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameMouseClicked(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        txtsurname.setText("example: surname");
        txtsurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsurnameFocusLost(evt);
            }
        });
        txtsurname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsurnameMouseClicked(evt);
            }
        });
        txtsurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsurnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsurnameKeyReleased(evt);
            }
        });

        checkDNI.setPreferredSize(new java.awt.Dimension(30, 30));

        checkpass.setPreferredSize(new java.awt.Dimension(30, 30));

        checkavatar.setPreferredSize(new java.awt.Dimension(30, 30));

        checkuser.setPreferredSize(new java.awt.Dimension(30, 30));

        checkname.setPreferredSize(new java.awt.Dimension(30, 30));

        checkstate.setPreferredSize(new java.awt.Dimension(30, 30));

        checksurname.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabel26.setText("Correo electronico:");

        jLabel27.setText("Telefono movil:");

        jLabel28.setText("Fecha de nacimiento:");

        jLabel29.setText("Compras:");

        jLabel30.setText("Dtos:");

        jLabel31.setText("Premium:");

        jLabel32.setText("Tipo de cliente:");

        txtdatebirthday.setDateFormatString(ClassConfig.getInstance().getDate());

        txtmobilephone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmobilephoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmobilephoneFocusLost(evt);
            }
        });
        txtmobilephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmobilephoneMouseClicked(evt);
            }
        });
        txtmobilephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmobilephoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmobilephoneKeyReleased(evt);
            }
        });

        txtemail.setText("example@example.com");
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemailMouseClicked(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        txtdtos.setText("example: 100");
        txtdtos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdtosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdtosFocusLost(evt);
            }
        });
        txtdtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdtosMouseClicked(evt);
            }
        });
        txtdtos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdtosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdtosKeyReleased(evt);
            }
        });

        txttype_client.setText("example: A1");
        txttype_client.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttype_clientFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttype_clientFocusLost(evt);
            }
        });
        txttype_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttype_clientMouseClicked(evt);
            }
        });
        txttype_client.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttype_clientKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttype_clientKeyReleased(evt);
            }
        });

        checkemail.setPreferredSize(new java.awt.Dimension(30, 30));

        checkmobilephone.setPreferredSize(new java.awt.Dimension(30, 30));

        checkdatebirthday.setPreferredSize(new java.awt.Dimension(30, 30));

        checkshopping.setPreferredSize(new java.awt.Dimension(30, 30));

        checkpremium.setPreferredSize(new java.awt.Dimension(30, 30));

        checkdtos.setPreferredSize(new java.awt.Dimension(30, 30));

        checktype_client.setPreferredSize(new java.awt.Dimension(30, 30));

        txtshopping.setText("example: 1000.00");
        txtshopping.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtshoppingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtshoppingFocusLost(evt);
            }
        });
        txtshopping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtshoppingMouseClicked(evt);
            }
        });
        txtshopping.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtshoppingKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtshoppingKeyReleased(evt);
            }
        });

        grouppremium.add(premiumtrue);
        premiumtrue.setSelected(true);
        premiumtrue.setText("Premium");

        grouppremium.add(premiumfalse);
        premiumfalse.setText("No premium");

        showpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/ojo.png"))); // NOI18N
        showpass.setPreferredSize(new java.awt.Dimension(30, 30));
        showpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showpassMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showpassMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(statetrue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statefalse))
                    .addComponent(txtname)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtavatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnavatar))
                    .addComponent(txtsurname)
                    .addComponent(txtDNI)
                    .addComponent(txtuser)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtpass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checkavatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checkpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checkuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checkDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checkstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checkname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checksurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmobilephone, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtdatebirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdtos)
                    .addComponent(txtemail)
                    .addComponent(txttype_client)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(premiumtrue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(premiumfalse))
                    .addComponent(txtshopping))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkmobilephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkdatebirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkshopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkpremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkdtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checktype_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(txtmobilephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkmobilephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(checkpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel28))
                                    .addComponent(txtdatebirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(checkdatebirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtavatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnavatar)
                            .addComponent(checkavatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(txtshopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(checkshopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(statetrue)
                    .addComponent(statefalse)
                    .addComponent(checkstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtdtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkdtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(checkpremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(premiumtrue)
                    .addComponent(premiumfalse))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checksurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txttype_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checktype_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblajustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajustesMouseEntered
        
    }//GEN-LAST:event_lblajustesMouseEntered

    private void lblajustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajustesMouseExited
        
    }//GEN-LAST:event_lblajustesMouseExited

    private void lblusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuarioMouseEntered
        
    }//GEN-LAST:event_lblusuarioMouseEntered

    private void lblusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuarioMouseExited
        
    }//GEN-LAST:event_lblusuarioMouseExited

    private void lblclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseEntered
        
    }//GEN-LAST:event_lblclienteMouseEntered

    private void lblclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseExited
        
    }//GEN-LAST:event_lblclienteMouseExited

    private void lbladministradorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladministradorMouseEntered
        
    }//GEN-LAST:event_lbladministradorMouseEntered

    private void lbladministradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladministradorMouseExited
        
    }//GEN-LAST:event_lbladministradorMouseExited

    private void lbladministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladministradorMouseClicked
        
    }//GEN-LAST:event_lbladministradorMouseClicked

    private void lblajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajustesMouseClicked
        
    }//GEN-LAST:event_lblajustesMouseClicked

    private void lblclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseClicked
        
    }//GEN-LAST:event_lblclienteMouseClicked

    private void lblusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuarioMouseClicked
        
    }//GEN-LAST:event_lblusuarioMouseClicked

    private void lblinicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicioMouseEntered
        
    }//GEN-LAST:event_lblinicioMouseEntered

    private void lblinicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicioMouseExited
        
    }//GEN-LAST:event_lblinicioMouseExited

    private void lblinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicioMouseClicked
        
    }//GEN-LAST:event_lblinicioMouseClicked

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        
    }//GEN-LAST:event_btncancelarActionPerformed

    private void lblvolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolverMouseEntered
        
    }//GEN-LAST:event_lblvolverMouseEntered

    private void lblvolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolverMouseExited
        
    }//GEN-LAST:event_lblvolverMouseExited

    private void lblvolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolverMouseClicked
        
    }//GEN-LAST:event_lblvolverMouseClicked

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void txtDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDNIMouseClicked
        
    }//GEN-LAST:event_txtDNIMouseClicked

    private void txtDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIFocusGained
        
    }//GEN-LAST:event_txtDNIFocusGained

    private void txtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyPressed
        
    }//GEN-LAST:event_txtDNIKeyPressed

    private void txtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyReleased
        
    }//GEN-LAST:event_txtDNIKeyReleased

    private void txtDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIFocusLost
        
    }//GEN-LAST:event_txtDNIFocusLost

    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked
        
    }//GEN-LAST:event_txtuserMouseClicked

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
        
    }//GEN-LAST:event_txtuserFocusGained

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyReleased
        
    }//GEN-LAST:event_txtuserKeyReleased

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
        
    }//GEN-LAST:event_txtuserFocusLost

    private void txtpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMouseClicked
        
    }//GEN-LAST:event_txtpassMouseClicked

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        
    }//GEN-LAST:event_txtpassFocusGained

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        
    }//GEN-LAST:event_txtpassKeyReleased

    private void txtpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusLost
        
    }//GEN-LAST:event_txtpassFocusLost

    private void txtnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMouseClicked
        
    }//GEN-LAST:event_txtnameMouseClicked

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        
    }//GEN-LAST:event_txtnameFocusLost

    private void txtsurnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsurnameMouseClicked
        
    }//GEN-LAST:event_txtsurnameMouseClicked

    private void txtsurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsurnameFocusGained
        
    }//GEN-LAST:event_txtsurnameFocusGained

    private void txtsurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsurnameKeyPressed
        
    }//GEN-LAST:event_txtsurnameKeyPressed

    private void txtsurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsurnameKeyReleased
        
    }//GEN-LAST:event_txtsurnameKeyReleased

    private void txtsurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsurnameFocusLost
        
    }//GEN-LAST:event_txtsurnameFocusLost

    private void txtemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseClicked
        
    }//GEN-LAST:event_txtemailMouseClicked

    private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
        
    }//GEN-LAST:event_txtemailFocusGained

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        
    }//GEN-LAST:event_txtemailFocusLost

    private void txtmobilephoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmobilephoneMouseClicked
        
    }//GEN-LAST:event_txtmobilephoneMouseClicked

    private void txtmobilephoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmobilephoneFocusGained
        
    }//GEN-LAST:event_txtmobilephoneFocusGained

    private void txtmobilephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobilephoneKeyPressed
        
    }//GEN-LAST:event_txtmobilephoneKeyPressed

    private void txtmobilephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobilephoneKeyReleased
        
    }//GEN-LAST:event_txtmobilephoneKeyReleased

    private void txtmobilephoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmobilephoneFocusLost
        
    }//GEN-LAST:event_txtmobilephoneFocusLost

    private void txtshoppingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtshoppingMouseClicked
        
    }//GEN-LAST:event_txtshoppingMouseClicked

    private void txtshoppingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtshoppingFocusGained
        
    }//GEN-LAST:event_txtshoppingFocusGained

    private void txtshoppingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtshoppingKeyPressed
        
    }//GEN-LAST:event_txtshoppingKeyPressed

    private void txtshoppingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtshoppingKeyReleased
        
    }//GEN-LAST:event_txtshoppingKeyReleased

    private void txtshoppingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtshoppingFocusLost
        
    }//GEN-LAST:event_txtshoppingFocusLost

    private void txtdtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdtosMouseClicked
        
    }//GEN-LAST:event_txtdtosMouseClicked

    private void txtdtosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdtosFocusGained
        
    }//GEN-LAST:event_txtdtosFocusGained

    private void txtdtosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdtosKeyPressed
        
    }//GEN-LAST:event_txtdtosKeyPressed

    private void txtdtosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdtosKeyReleased
        
    }//GEN-LAST:event_txtdtosKeyReleased

    private void txtdtosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdtosFocusLost
        
    }//GEN-LAST:event_txtdtosFocusLost

    private void txttype_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttype_clientMouseClicked
        
    }//GEN-LAST:event_txttype_clientMouseClicked

    private void txttype_clientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttype_clientFocusGained
        
    }//GEN-LAST:event_txttype_clientFocusGained

    private void txttype_clientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttype_clientKeyPressed
        
    }//GEN-LAST:event_txttype_clientKeyPressed

    private void txttype_clientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttype_clientKeyReleased
        
    }//GEN-LAST:event_txttype_clientKeyReleased

    private void txttype_clientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttype_clientFocusLost
        
    }//GEN-LAST:event_txttype_clientFocusLost

    private void showpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassMouseExited
        
    }//GEN-LAST:event_showpassMouseExited

    private void showpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassMouseEntered
        
    }//GEN-LAST:event_showpassMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFileChooser JFC_avatar;
    public static javax.swing.JButton btnaceptar;
    public static javax.swing.JButton btnavatar;
    public static javax.swing.JButton btncancelar;
    public static javax.swing.JLabel checkDNI;
    public static javax.swing.JLabel checkavatar;
    public static javax.swing.JLabel checkdatebirthday;
    public static javax.swing.JLabel checkdtos;
    public static javax.swing.JLabel checkemail;
    public static javax.swing.JLabel checkmobilephone;
    public static javax.swing.JLabel checkname;
    public static javax.swing.JLabel checkpass;
    public static javax.swing.JLabel checkpremium;
    public static javax.swing.JLabel checkshopping;
    public static javax.swing.JLabel checkstate;
    public static javax.swing.JLabel checksurname;
    public static javax.swing.JLabel checktype_client;
    public static javax.swing.JLabel checkuser;
    private javax.swing.ButtonGroup grouppremium;
    private javax.swing.ButtonGroup groupstate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JLabel lbladministrador;
    public static javax.swing.JLabel lblajustes;
    public static javax.swing.JLabel lblcliente;
    public static javax.swing.JLabel lblconfiguracion;
    public static javax.swing.JLabel lblinicio;
    public static javax.swing.JLabel lblinicios;
    public static javax.swing.JLabel lbltitulo;
    public static javax.swing.JLabel lblusuario;
    public static javax.swing.JLabel lblusuarios;
    public static javax.swing.JLabel lblvolver;
    public static javax.swing.JRadioButton premiumfalse;
    public static javax.swing.JRadioButton premiumtrue;
    public static javax.swing.JLabel showpass;
    public static javax.swing.JRadioButton statefalse;
    public static javax.swing.JRadioButton statetrue;
    public static javax.swing.JTextField txtDNI;
    public static javax.swing.JTextField txtavatar;
    public static javax.swing.JLabel txtconfirm;
    public static com.toedter.calendar.JDateChooser txtdatebirthday;
    public static javax.swing.JTextField txtdtos;
    public static javax.swing.JTextField txtemail;
    public static javax.swing.JTextField txtmobilephone;
    public static javax.swing.JTextField txtname;
    public static javax.swing.JPasswordField txtpass;
    public static javax.swing.JTextField txtshopping;
    public static javax.swing.JTextField txtsurname;
    public static javax.swing.JTextField txttype_client;
    public static javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

}
