/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.module.admin.view;

import framework.module.admin.model.classes.language.Language_admin;

/**
 *
 * @author angel
 */
public class List_admin extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Menu
     */
    public List_admin() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpanelFondo = new javax.swing.JPanel();
        jPanelLateral = new javax.swing.JPanel();
        lblusuarios = new javax.swing.JLabel();
        lbladministrador = new javax.swing.JLabel();
        lblcliente = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblconfiguracion = new javax.swing.JLabel();
        lblajustes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblinicios = new javax.swing.JLabel();
        lblinicio = new javax.swing.JLabel();
        jPanelTitulo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelBase = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jPanelTabla = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblupdate = new javax.swing.JLabel();
        lblcreate = new javax.swing.JLabel();
        lbldelete = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblsize = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ANTERIOR = new javax.swing.JButton();
        SIGUIENTE = new javax.swing.JButton();
        CAJA = new javax.swing.JTextField();
        primero = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbljson = new javax.swing.JLabel();
        lblxml = new javax.swing.JLabel();
        lbltxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelFondo.setLayout(new java.awt.BorderLayout());

        jPanelLateral.setBackground(java.awt.Color.white);

        lblusuarios.setFont(new java.awt.Font("Purisa", 3, 15)); // NOI18N
        lblusuarios.setForeground(java.awt.Color.blue);
        lblusuarios.setText(Language_admin.getInstance().getProperty("users"));

        lbladministrador.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lbladministrador.setForeground(java.awt.Color.cyan);
        lbladministrador.setText(Language_admin.getInstance().getProperty("administrator"));
        lbladministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladministradorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbladministradorMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbladministradorMouseEntered(evt);
            }
        });

        lblcliente.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblcliente.setForeground(java.awt.Color.cyan);
        lblcliente.setText(Language_admin.getInstance().getProperty("client"));
        lblcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblclienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblclienteMouseEntered(evt);
            }
        });

        lblusuario.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblusuario.setForeground(java.awt.Color.cyan);
        lblusuario.setText(Language_admin.getInstance().getProperty("user"));
        lblusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblusuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblusuarioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblusuarioMouseEntered(evt);
            }
        });

        lblconfiguracion.setFont(new java.awt.Font("Purisa", 3, 15)); // NOI18N
        lblconfiguracion.setForeground(java.awt.Color.blue);
        lblconfiguracion.setText(Language_admin.getInstance().getProperty("configuration"));

        lblajustes.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblajustes.setForeground(java.awt.Color.cyan);
        lblajustes.setText(Language_admin.getInstance().getProperty("setting"));
        lblajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblajustesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblajustesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblajustesMouseEntered(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblinicios.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblinicios.setForeground(java.awt.Color.blue);
        lblinicios.setText(Language_admin.getInstance().getProperty("start"));

        lblinicio.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        lblinicio.setForeground(java.awt.Color.cyan);
        lblinicio.setText(Language_admin.getInstance().getProperty("start"));
        lblinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblinicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblinicioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblinicioMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinicios)
                    .addComponent(lblusuarios)
                    .addComponent(lblconfiguracion)
                    .addGroup(jPanelLateralLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinicio)
                            .addComponent(lblcliente)
                            .addComponent(lbladministrador)
                            .addComponent(lblusuario)
                            .addComponent(lblajustes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblinicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinicio)
                .addGap(18, 18, 18)
                .addComponent(lblusuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbladministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblusuario)
                .addGap(18, 18, 18)
                .addComponent(lblconfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblajustes)
                .addContainerGap(185, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        jpanelFondo.add(jPanelLateral, java.awt.BorderLayout.WEST);

        jPanelTitulo.setBackground(java.awt.Color.white);
        jPanelTitulo.setLayout(new java.awt.BorderLayout());

        lbltitulo.setBackground(java.awt.Color.white);
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/titulo.JPG"))); // NOI18N
        jPanelTitulo.add(lbltitulo, java.awt.BorderLayout.CENTER);
        jPanelTitulo.add(jSeparator2, java.awt.BorderLayout.SOUTH);

        jpanelFondo.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelBase.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1082, Short.MAX_VALUE)
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jpanelFondo.add(jPanelBase, java.awt.BorderLayout.SOUTH);

        jPanelCentral.setBackground(java.awt.Color.white);
        jPanelCentral.setLayout(new java.awt.BorderLayout());

        jPanelTabla.setBackground(java.awt.Color.white);
        jPanelTabla.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(java.awt.Color.white);

        lblupdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/color_line.png"))); // NOI18N
        lblupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblupdateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblupdateMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblupdateMouseEntered(evt);
            }
        });

        lblcreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/edit_add.png"))); // NOI18N
        lblcreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcreateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcreateMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcreateMouseEntered(evt);
            }
        });

        lbldelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/edit_remove.png"))); // NOI18N
        lbldelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldeleteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldeleteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldeleteMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jPanelTabla.add(jPanel9, java.awt.BorderLayout.EAST);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TABLA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLAMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TABLA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTabla.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelCentral.add(jPanelTabla, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(java.awt.Color.white);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(Language_admin.getInstance().getProperty("find")));

        jLabel1.setText(Language_admin.getInstance().getProperty("find2"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        lblsize.setText("jLabel3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ANTERIOR.setText("<");
        ANTERIOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTERIORActionPerformed(evt);
            }
        });

        SIGUIENTE.setText(">");
        SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGUIENTEActionPerformed(evt);
            }
        });

        CAJA.setEditable(false);
        CAJA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAJA.setPreferredSize(new java.awt.Dimension(140, 20));

        primero.setText("|<");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });

        ultimo.setText(">|");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(primero)
                .addGap(18, 18, 18)
                .addComponent(ANTERIOR)
                .addGap(18, 18, 18)
                .addComponent(CAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SIGUIENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ultimo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ANTERIOR)
                        .addComponent(primero))
                    .addComponent(CAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SIGUIENTE)
                        .addComponent(ultimo))))
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20", "50", "100" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setText(Language_admin.getInstance().getProperty("entries"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblsize, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel7.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(java.awt.Color.white);
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(Language_admin.getInstance().getProperty("save")));
        jPanel11.setLayout(new java.awt.GridLayout(1, 3));

        lbljson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbljson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/json.png"))); // NOI18N
        lbljson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbljsonMouseClicked(evt);
            }
        });
        jPanel11.add(lbljson);

        lblxml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblxml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/xml.jpg"))); // NOI18N
        lblxml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblxmlMouseClicked(evt);
            }
        });
        jPanel11.add(lblxml);

        lbltxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/txt.jpg"))); // NOI18N
        lbltxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltxtMouseClicked(evt);
            }
        });
        jPanel11.add(lbltxt);

        jPanel7.add(jPanel11, java.awt.BorderLayout.EAST);

        jPanelCentral.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jpanelFondo.add(jPanelCentral, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jpanelFondo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbladministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladministradorMouseClicked
        
    }//GEN-LAST:event_lbladministradorMouseClicked

    private void lbladministradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladministradorMouseExited
        
    }//GEN-LAST:event_lbladministradorMouseExited

    private void lbladministradorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladministradorMouseEntered
        
    }//GEN-LAST:event_lbladministradorMouseEntered

    private void lblclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseClicked
        
    }//GEN-LAST:event_lblclienteMouseClicked

    private void lblclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseExited
        
    }//GEN-LAST:event_lblclienteMouseExited

    private void lblclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseEntered
        
    }//GEN-LAST:event_lblclienteMouseEntered

    private void lblusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuarioMouseClicked
        
    }//GEN-LAST:event_lblusuarioMouseClicked

    private void lblusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuarioMouseExited
        
    }//GEN-LAST:event_lblusuarioMouseExited

    private void lblusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuarioMouseEntered
        
    }//GEN-LAST:event_lblusuarioMouseEntered

    private void lblajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajustesMouseClicked
        
    }//GEN-LAST:event_lblajustesMouseClicked

    private void lblajustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajustesMouseExited
        
    }//GEN-LAST:event_lblajustesMouseExited

    private void lblajustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajustesMouseEntered
        
    }//GEN-LAST:event_lblajustesMouseEntered

    private void lblinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicioMouseClicked
        
    }//GEN-LAST:event_lblinicioMouseClicked

    private void lblinicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicioMouseExited
        
    }//GEN-LAST:event_lblinicioMouseExited

    private void lblinicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicioMouseEntered
        
    }//GEN-LAST:event_lblinicioMouseEntered

    private void lblcreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcreateMouseEntered
        
    }//GEN-LAST:event_lblcreateMouseEntered

    private void lblcreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcreateMouseExited
        
    }//GEN-LAST:event_lblcreateMouseExited

    private void lbldeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldeleteMouseEntered
        
    }//GEN-LAST:event_lbldeleteMouseEntered

    private void lbldeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldeleteMouseExited
        
    }//GEN-LAST:event_lbldeleteMouseExited

    private void lblupdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblupdateMouseEntered
        
    }//GEN-LAST:event_lblupdateMouseEntered

    private void lblupdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblupdateMouseExited
        
    }//GEN-LAST:event_lblupdateMouseExited

    private void lblcreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcreateMouseClicked
        
    }//GEN-LAST:event_lblcreateMouseClicked

    private void lbljsonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbljsonMouseClicked
        
    }//GEN-LAST:event_lbljsonMouseClicked

    private void lblxmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblxmlMouseClicked
        
    }//GEN-LAST:event_lblxmlMouseClicked

    private void lbltxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltxtMouseClicked
        
    }//GEN-LAST:event_lbltxtMouseClicked

    private void lblupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblupdateMouseClicked
        
    }//GEN-LAST:event_lblupdateMouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        
    }//GEN-LAST:event_ultimoActionPerformed

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        
    }//GEN-LAST:event_primeroActionPerformed

    private void SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGUIENTEActionPerformed
        
    }//GEN-LAST:event_SIGUIENTEActionPerformed

    private void ANTERIORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTERIORActionPerformed
        
    }//GEN-LAST:event_ANTERIORActionPerformed

    private void lbldeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldeleteMouseClicked
        
    }//GEN-LAST:event_lbldeleteMouseClicked

    private void TABLAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLAMouseClicked
        
    }//GEN-LAST:event_TABLAMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ANTERIOR;
    public static javax.swing.JTextField CAJA;
    public static javax.swing.JButton SIGUIENTE;
    public static javax.swing.JTable TABLA;
    public static javax.swing.JComboBox jComboBox2;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelTitulo;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpanelFondo;
    public static javax.swing.JLabel lbladministrador;
    public static javax.swing.JLabel lblajustes;
    public static javax.swing.JLabel lblcliente;
    public static javax.swing.JLabel lblconfiguracion;
    public static javax.swing.JLabel lblcreate;
    public static javax.swing.JLabel lbldelete;
    public static javax.swing.JLabel lblinicio;
    public static javax.swing.JLabel lblinicios;
    public static javax.swing.JLabel lbljson;
    public static javax.swing.JLabel lblsize;
    public static javax.swing.JLabel lbltitulo;
    public static javax.swing.JLabel lbltxt;
    public static javax.swing.JLabel lblupdate;
    public static javax.swing.JLabel lblusuario;
    public static javax.swing.JLabel lblusuarios;
    public static javax.swing.JLabel lblxml;
    public static javax.swing.JButton primero;
    public static javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables

}
