/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.module.config.view;

import framework.module.admin.model.functions.json_auto_admin;
import framework.module.menu.view.*;
import framework.module.admin.view.List_admin;
import framework.module.client.model.functions.json_auto_client;
import framework.module.client.view.List_client;
import framework.module.userregister.model.functions.json_auto_userregister;
import framework.module.userregister.view.List_userregister;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Config() {
        initComponents();
        
        this.setTitle("Framework");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); //la aplicación se abre maximizada
	//this.setLocationRelativeTo(null);
	//this.setSize(525,425);//ancho x alto
	//this.setResizable(false);
	//Image icono=Toolkit.getDefaultToolkit().getImage("p1.jpg");
	//this.setIconImage(icono);
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                json_auto_admin.savejson_admin();
                json_auto_client.savejson_client();
                json_auto_userregister.savejson_userregister();
                JOptionPane.showMessageDialog(null,"Saliendo de la aplicación");
                dispose();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelcurrency = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        € = new javax.swing.JRadioButton();
        $ = new javax.swing.JRadioButton();
        £ = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblvolver = new javax.swing.JLabel();
        panellanguage = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        english = new javax.swing.JRadioButton();
        castellano = new javax.swing.JRadioButton();
        valencia = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblvolver1 = new javax.swing.JLabel();
        paneldate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        date1 = new javax.swing.JRadioButton();
        date2 = new javax.swing.JRadioButton();
        date3 = new javax.swing.JRadioButton();
        date4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lblvolver2 = new javax.swing.JLabel();
        paneltheme = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        metal = new javax.swing.JRadioButton();
        gtk = new javax.swing.JRadioButton();
        motif = new javax.swing.JRadioButton();
        ninbus = new javax.swing.JRadioButton();
        windowsclassic = new javax.swing.JRadioButton();
        windows = new javax.swing.JRadioButton();
        mac = new javax.swing.JRadioButton();
        aqua = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lblvolver3 = new javax.swing.JLabel();
        paneldecimal = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        decimal1 = new javax.swing.JRadioButton();
        decimal2 = new javax.swing.JRadioButton();
        decimal3 = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        lblvolver4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        lblvolver5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/titulo.JPG"))); // NOI18N
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);
        jPanel2.add(jSeparator2, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(java.awt.Color.white);

        jLabel2.setFont(new java.awt.Font("Purisa", 3, 15)); // NOI18N
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("Usuarios");

        jLabel3.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.cyan);
        jLabel3.setText("Administrador");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.cyan);
        jLabel4.setText("Clientes");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.cyan);
        jLabel5.setText("Usuarios");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Purisa", 3, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.blue);
        jLabel6.setText("Configuración");

        jLabel7.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jLabel7.setForeground(java.awt.Color.cyan);
        jLabel7.setText("Ajustes");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel15.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jLabel15.setForeground(java.awt.Color.blue);
        jLabel15.setText("Inicio");

        jLabel16.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jLabel16.setForeground(java.awt.Color.cyan);
        jLabel16.setText("Inicio");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(240, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jTabbedPane1.setBackground(java.awt.Color.white);
        jTabbedPane1.setOpaque(true);

        panelcurrency.setBackground(java.awt.Color.white);

        jLabel9.setText("Seleccione la moneda deseada:");

        €.setText("EURO");

        $.setText("DOLLAR");

        £.setText("LIBRA ESTERLINA");

        jButton1.setText("Aceptar");

        jButton2.setText("Cancelar");

        lblvolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png"))); // NOI18N
        lblvolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvolverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvolverMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvolverMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelcurrencyLayout = new javax.swing.GroupLayout(panelcurrency);
        panelcurrency.setLayout(panelcurrencyLayout);
        panelcurrencyLayout.setHorizontalGroup(
            panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcurrencyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcurrencyLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jLabel9)
                    .addComponent(€)
                    .addComponent($)
                    .addComponent(£))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 635, Short.MAX_VALUE)
                .addComponent(lblvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelcurrencyLayout.setVerticalGroup(
            panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcurrencyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcurrencyLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(€)
                        .addGap(18, 18, 18)
                        .addComponent($)
                        .addGap(18, 18, 18)
                        .addComponent(£)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addGroup(panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcurrencyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblvolver)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Moneda", panelcurrency);

        panellanguage.setBackground(java.awt.Color.white);

        jLabel10.setText("Seleccione el idioma deseado:");

        english.setText("ENGLISH");

        castellano.setText("CASTELLANO");

        valencia.setText("VALENCIÀ");

        jButton3.setText("Aceptar");

        jButton4.setText("Cancelar");

        lblvolver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png"))); // NOI18N
        lblvolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvolver1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvolver1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvolver1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panellanguageLayout = new javax.swing.GroupLayout(panellanguage);
        panellanguage.setLayout(panellanguageLayout);
        panellanguageLayout.setHorizontalGroup(
            panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellanguageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellanguageLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 693, Short.MAX_VALUE)
                        .addComponent(lblvolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panellanguageLayout.createSequentialGroup()
                        .addGroup(panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(english)
                            .addComponent(valencia)
                            .addComponent(castellano))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panellanguageLayout.setVerticalGroup(
            panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellanguageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panellanguageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblvolver1))
                    .addGroup(panellanguageLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(english)
                        .addGap(18, 18, 18)
                        .addComponent(castellano)
                        .addGap(18, 18, 18)
                        .addComponent(valencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addGroup(panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Idioma", panellanguage);

        paneldate.setBackground(java.awt.Color.white);

        jLabel11.setText("Seleccione el formato de la fecha deseada:");

        date1.setText("dd/MM/yyyy");

        date2.setText("dd-MM-yyyy");

        date3.setText("yyyy/MM/dd");

        date4.setText("yyyy-MM-dd");

        jButton5.setText("Aceptar");

        jButton6.setText("Cancelar");

        lblvolver2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png"))); // NOI18N
        lblvolver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvolver2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvolver2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvolver2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout paneldateLayout = new javax.swing.GroupLayout(paneldate);
        paneldate.setLayout(paneldateLayout);
        paneldateLayout.setHorizontalGroup(
            paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldateLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblvolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldateLayout.createSequentialGroup()
                        .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(date1)
                            .addComponent(date2)
                            .addComponent(date3)
                            .addComponent(date4))
                        .addGap(0, 624, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneldateLayout.setVerticalGroup(
            paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneldateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblvolver2))
                    .addGroup(paneldateLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(date1)
                        .addGap(18, 18, 18)
                        .addComponent(date2)
                        .addGap(18, 18, 18)
                        .addComponent(date3)
                        .addGap(18, 18, 18)
                        .addComponent(date4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                        .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fecha", paneldate);

        paneltheme.setBackground(java.awt.Color.white);

        jLabel12.setText("PRECAUCIÓN: puede ser que no funciones todas las opciones");

        jLabel13.setText("Seleccione la apariencia deseada:");

        metal.setText("METAL");

        gtk.setText("GTK");

        motif.setText("MOTIF");

        ninbus.setText("NINBUS");

        windowsclassic.setText("WINDOWS CLASSIC");

        windows.setText("WINDOWS");

        mac.setText("MAC");

        aqua.setText("MAC AQUA");

        jButton7.setText("Aceptar");

        jButton8.setText("Cancelar");

        lblvolver3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvolver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png"))); // NOI18N
        lblvolver3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvolver3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvolver3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvolver3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelthemeLayout = new javax.swing.GroupLayout(paneltheme);
        paneltheme.setLayout(panelthemeLayout);
        panelthemeLayout.setHorizontalGroup(
            panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelthemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addGroup(panelthemeLayout.createSequentialGroup()
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gtk)
                            .addComponent(motif)
                            .addComponent(ninbus))
                        .addGap(136, 136, 136)
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mac)
                            .addComponent(windows)
                            .addGroup(panelthemeLayout.createSequentialGroup()
                                .addComponent(aqua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                                .addComponent(lblvolver3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(windowsclassic)))
                    .addComponent(metal)
                    .addGroup(panelthemeLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        panelthemeLayout.setVerticalGroup(
            panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelthemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelthemeLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metal)
                            .addComponent(windowsclassic))
                        .addGap(18, 18, 18)
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gtk)
                            .addComponent(windows))
                        .addGap(18, 18, 18)
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(motif)
                            .addComponent(mac))
                        .addGap(18, 18, 18)
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ninbus)
                            .addComponent(aqua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelthemeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblvolver3)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Apariencia", paneltheme);

        paneldecimal.setBackground(java.awt.Color.white);

        jLabel14.setText("Seleccione la cantidad de decimales deseada:");

        decimal1.setText("1 DECIMAL");

        decimal2.setText("2 DECIMALES");

        decimal3.setText("3 DECIMALES");

        jButton9.setText("Aceptar");

        jButton10.setText("Cancelar");

        lblvolver4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvolver4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png"))); // NOI18N
        lblvolver4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvolver4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvolver4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvolver4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout paneldecimalLayout = new javax.swing.GroupLayout(paneldecimal);
        paneldecimal.setLayout(paneldecimalLayout);
        paneldecimalLayout.setHorizontalGroup(
            paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldecimalLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblvolver4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldecimalLayout.createSequentialGroup()
                        .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(decimal1)
                            .addComponent(decimal2)
                            .addComponent(decimal3))
                        .addGap(0, 607, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneldecimalLayout.setVerticalGroup(
            paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneldecimalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblvolver4))
                    .addGroup(paneldecimalLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(decimal1)
                        .addGap(18, 18, 18)
                        .addComponent(decimal2)
                        .addGap(18, 18, 18)
                        .addComponent(decimal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Decimal", paneldecimal);

        jPanel6.setBackground(java.awt.Color.white);

        jButton11.setText("Guardar configuración");

        jButton12.setText("Abrir configuración");

        lblvolver5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvolver5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png"))); // NOI18N
        lblvolver5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvolver5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvolver5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvolver5MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton11)
                .addGap(69, 69, 69)
                .addComponent(jButton12)
                .addContainerGap(508, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblvolver5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(lblvolver5)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Guardar", jPanel6);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblvolver5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver5MouseEntered
        lblvolver5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver.png")));
    }//GEN-LAST:event_lblvolver5MouseEntered

    private void lblvolver5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver5MouseExited
        lblvolver5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png")));
    }//GEN-LAST:event_lblvolver5MouseExited

    private void lblvolver5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver5MouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_lblvolver5MouseClicked

    private void lblvolver4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver4MouseEntered
        lblvolver4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver.png")));
    }//GEN-LAST:event_lblvolver4MouseEntered

    private void lblvolver4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver4MouseExited
        lblvolver4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png")));
    }//GEN-LAST:event_lblvolver4MouseExited

    private void lblvolver4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver4MouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_lblvolver4MouseClicked

    private void lblvolver3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver3MouseEntered
        lblvolver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver.png")));
    }//GEN-LAST:event_lblvolver3MouseEntered

    private void lblvolver3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver3MouseExited
        lblvolver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png")));
    }//GEN-LAST:event_lblvolver3MouseExited

    private void lblvolver3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver3MouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_lblvolver3MouseClicked

    private void lblvolver2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver2MouseEntered
        lblvolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver.png")));
    }//GEN-LAST:event_lblvolver2MouseEntered

    private void lblvolver2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver2MouseExited
        lblvolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png")));
    }//GEN-LAST:event_lblvolver2MouseExited

    private void lblvolver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver2MouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_lblvolver2MouseClicked

    private void lblvolver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver1MouseEntered
        lblvolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver.png")));
    }//GEN-LAST:event_lblvolver1MouseEntered

    private void lblvolver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver1MouseExited
        lblvolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png")));
    }//GEN-LAST:event_lblvolver1MouseExited

    private void lblvolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolver1MouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_lblvolver1MouseClicked

    private void lblvolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolverMouseEntered
        lblvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver.png")));
    }//GEN-LAST:event_lblvolverMouseEntered

    private void lblvolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolverMouseExited
        lblvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/volver_bn.png")));
    }//GEN-LAST:event_lblvolverMouseExited

    private void lblvolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvolverMouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_lblvolverMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new List_admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setForeground(java.awt.Color.cyan);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new List_client().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(java.awt.Color.cyan);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new List_userregister().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(java.awt.Color.cyan);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new Config().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(java.awt.Color.cyan);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        jLabel10.setForeground(java.awt.Color.cyan);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel10.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_jLabel16MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton $;
    public static javax.swing.JRadioButton aqua;
    public static javax.swing.JRadioButton castellano;
    public static javax.swing.JRadioButton date1;
    public static javax.swing.JRadioButton date2;
    public static javax.swing.JRadioButton date3;
    public static javax.swing.JRadioButton date4;
    public static javax.swing.JRadioButton decimal1;
    public static javax.swing.JRadioButton decimal2;
    public static javax.swing.JRadioButton decimal3;
    public static javax.swing.JRadioButton english;
    public static javax.swing.JRadioButton gtk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblvolver;
    private javax.swing.JLabel lblvolver1;
    private javax.swing.JLabel lblvolver2;
    private javax.swing.JLabel lblvolver3;
    private javax.swing.JLabel lblvolver4;
    private javax.swing.JLabel lblvolver5;
    public static javax.swing.JRadioButton mac;
    public static javax.swing.JRadioButton metal;
    public static javax.swing.JRadioButton motif;
    public static javax.swing.JRadioButton ninbus;
    private javax.swing.JPanel panelcurrency;
    private javax.swing.JPanel paneldate;
    private javax.swing.JPanel paneldecimal;
    private javax.swing.JPanel panellanguage;
    private javax.swing.JPanel paneltheme;
    public static javax.swing.JRadioButton valencia;
    public static javax.swing.JRadioButton windows;
    public static javax.swing.JRadioButton windowsclassic;
    public static javax.swing.JRadioButton £;
    public static javax.swing.JRadioButton €;
    // End of variables declaration//GEN-END:variables

}
